# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

target 'ChatRoom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChatRoom

  target 'ChatRoomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ChatRoom-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChatRoom-tvOS

  target 'ChatRoom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
